var mongoose = require('mongoose');
var textSearch = require("mongoose-text-search");

var cubeComposite_instanceSchema = new mongoose.Schema({
    CIKEY: Number,
	CREATION_DATE: String,
	CREATOR: String,
	MODIFY_DATE: String,
	MODIFIER: String,
	STATE: String,
	PRIORITY: String,
	TITLE: String,
	STATUS: String,
	STAGE: String,
	CONVERSATION_ID: String,
	ROOT_ID: String,
	PARENT_ID: String,
	SCOPE_REVISION: String,
	SCOPE_CSIZE: String,
	SCOPE_USIZE: String,
	PROCESS_TYPE: String,
	METADATA: String,
	EXT_STRING1: String,
	EXT_STRING2: String,
	EXT_INT1: String,
	TEST_RUN_ID: String,
	TEST_RUN_NAME: String,
	TEST_CASE: String,
	TEST_SUITE: String,
	ECID: String,
	CMPST_ID: Number,
	OUTCOME: String,
	TRACKING_LEVEL: String,
	AT_EVENT_ID: String,
	AT_DETAIL_ID: String,
	VERSION: String,
	AG_ROOT_ID: String,
	AG_MILESTONE_PATH: String,
	CACHE_VERSION: String,
	PARENT_REF_ID: String,
	COMPONENTTYPE: String,
	NOTM: String,
	COMPOSITE_NAME: String,
	DOMAIN_NAME: String,
	COMPONENT_NAME: String,
	COMPOSITE_LABEL: String,
	COMPOSITE_REVISION: String,
	CREATE_CLUSTER_NODE_ID: String,
	LAST_CLUSTER_NODE_ID: String,
	CPST_INST_CREATED_TIME: String,
	TENANT_ID: String,
	ECID: Number,
	COMPTITLE: String,
	ID: Number,
	PARENT_ID: String,
	CONVERSATION_ID: String,
	COMPOSITE_DN: String,
	SOURCE_NAME: String,
	SOURCE_TYPE: String,
	SOURCE_ACTION_TYPE: String,
	SOURCE_ACTION_NAME: String,
	BATCH_ID: String,
	BATCH_INDEX: String,
	BUSINESS_STATUS: String,
	INDEX1: String,
	INDEX2: String,
	INDEX3: String,
	INDEX4: String,
	INDEX5: String,
	INDEX6: String,
	TITLE: String,
	TAGS: String,
	TEST_RUN_NAME: String,
	TEST_RUN_ID: String,
	TEST_SUITE: String,
	TEST_CASE: String,
	STATE: String,
	LIVE_INSTANCES: String,
	STATE_COUNT: String,
	HAS_ASSOC: String,
	VERSION: String,
	PARTITION_DATE: String,
	TENANT_ID: String,
	CREATED_BY: String,
	CREATED_TIME: String,
	UPDATED_BY: String,
	UPDATED_TIME: String
	
},{ collection : 'cubeComposite_instance' });

cubeComposite_instanceSchema.plugin(textSearch);
cubeComposite_instanceSchema.index({
    COMPTITLE            :"text",
}, {
    name: "TITLE_text",
    weights: {
        COMPTITLE: 1,
    }
});


var cubeCompositeInstance = mongoose.model('cubeCompositeInstance', cubeComposite_instanceSchema);
module.exports = cubeCompositeInstance;